apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: haimmanos/vprofiledb:latest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data

      initContainers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for vprodb; sleep 2; done;']

      volumes:
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-0a0959cde3882f55f
          fsType: ext4

      # Node Affinity for ensuring the pod is deployed in the same zone as the volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1a # Availability zone of your EBS volume

      # Tolerations for control-plane taints and node readiness issues
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300

      # Adding a lifecycle hook to handle attachment delays
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "sleep 10"]

  nodeSelector:
    zone: us-east-1a # Ensure the pod is scheduled in the correct zone
