apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1 # Correct placement of replicas
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      nodeSelector: # Node selector under spec, not containers
        topology.kubernetes.io/zone: us-east-1a
      containers:
      - name: vprodb
        image: haimmanos/vprofiledb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
      volumes: # Volumes should be under spec, not containers
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-00cd0abd20ae2f925
          fsType: ext4

      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
