apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: haimmanos/vprofiledb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data

        # Adding lifecycle under the container's spec, not pod spec
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]

      initContainers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for vprodb; sleep 2; done;']

      volumes:
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-0a0959cde3882f55f
          fsType: ext4

      # NodeSelector should be placed inside the template spec
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a

      # Tolerations and affinity should also be inside the template spec
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1a # Adjust to your EBS volume's availability zone
